# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170213_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_reports_allowed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monthly_reports_allowed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_reports_allowed',
        ),
        migrations.AddField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(default=b'0', max_length=1),
        ),
    ]
