# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170214_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
