# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170214_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 15, 6, 54, 16, 588023, tzinfo=utc)),
        ),
    ]
