# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170215_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
