# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170214_1128'),
        ('api', '0030_auto_20170215_0656'),
    ]

    operations = [
    ]
