# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20170215_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_interval',
        ),
        migrations.RemoveField(
            model_name='check',
            name='set_nag',
        ),
    ]
