# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170215_0948'),
        ('api', '0033_auto_20170215_0854'),
    ]

    operations = [
    ]
